-- ==============================================================================
-- SCRIPT DE CONFIGURAÇÃO DA TABELA DE QUESTÕES NO SUPABASE
-- Execute este script no SQL Editor do Supabase para criar/atualizar a estrutura
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.questoes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PROVA" text,
    "Ordem" numeric,
    "Banca" text,
    "Disciplina" text,
    "Materia" text,
    "Tópico" text,
    "Assunto" text,
    "Dificuldade" text,
    "Status" text DEFAULT 'Ativa',
    "Texto de apoio" text,
    "Enunciado" text,
    "Pergunta problema" text,
    "Imagem_Enunciado" text,
    "Alternativa A" text,
    "Alternativa B" text,
    "Alternativa C" text,
    "Alternativa D" text,
    "Alternativa E" text,
    "Gabarito" text,
    "Comentário" text,
    created_at timestamp with time zone DEFAULT now()
);

-- Configuração de RLS (Row Level Security)
ALTER TABLE public.questoes ENABLE ROW LEVEL SECURITY;

-- Permitir leitura pública para que todos os alunos vejam as questões
CREATE POLICY "Permitir leitura pública das questões" ON public.questoes
    FOR SELECT USING (true);

-- Permitir inserção de questões (para a funcionalidade de importação via JSON)
CREATE POLICY "Permitir inserção de questões" ON public.questoes
    FOR INSERT WITH CHECK (true);

-- Permitir atualização de questões
CREATE POLICY "Permitir atualização de questões" ON public.questoes
    FOR UPDATE USING (true);

-- Permitir exclusão de questões
CREATE POLICY "Permitir exclusão de questões" ON public.questoes
    FOR DELETE USING (true);
